// src/routes/brew/+page.svelte
<script lang="ts">
    import { blur, fade, slide } from 'svelte/transition';
    import { flip } from 'svelte/animate';
    import PaletteCard from '$lib/components/PaletteCard.svelte';
    import BrewInput from '$lib/components/BrewInput.svelte';
    import Container from '$lib/components/Container.svelte';
    let isFetchingPalette: boolean = false;
    let brewInput: string = '';
    let palettes = [] as Palette[];
    let palettesDiv: HTMLElement;

    async function brew() {
        if (brewInput.length === 0) return;
        // Result the current palette
        isFetchingPalette = true;
        // Fetch the palette from the server
        let res = await fetch(`/api/brew?prompt=${brewInput}`, {
            method: 'GET'
        });
        let newPalette = await res.json();
        // Svelte doesn't rerender when you push to an array, so we need to create a new array with the new palette
        palettes = [newPalette, ...palettes];
        // Stop the loading animation
        isFetchingPalette = false;
    }

    // Client side length limit for the prompt. The server will also check this.
    $: {
        if (brewInput.length > 100) {
            brewInput = brewInput.slice(0, 100);
        }
    }
</script>

<div class="animate-fade-in flex flex-1 items-center transition-all duration-700">
    <Container size="small">
        <div class="my-10">
            <!-- Info -->
            {#if palettes.length === 0}
                <div class="flex flex-col items-center text-center" out:blur={{ duration: 800 }}>
                    <p class="font-serif text-3xl font-bold">Brew a palette</p>
                    <p class="mt-4 w-full max-w-[550px] text-base text-zinc-600 md:text-lg">Describe the theme of your colors, vibes, or use cases.</p>
                </div>
            {/if}
            <!-- Prompt -->
            <div class="mt-10">
                <div class="flex flex-col gap-2">
                    <BrewInput bind:value={brewInput} loading={isFetchingPalette} onBrew={() => brew()} />
                    <div class="flex w-full items-center justify-end gap-2">
                        {#if brewInput.length > 80}
                            <span class="text-sm font-medium text-zinc-500">{brewInput.length}/100</span>
                        {/if}
                    </div>
                </div>
            </div>
            <!-- Palettes -->
            {#if palettes.length > 0}
                <section class="mt-12 mb-16" in:fade={{ duration: 1000, delay: 700 }} bind:this={palettesDiv}>
                    <div class="flex flex-col gap-8">
                        {#each palettes as palette, index (palette.id)}
                            <div in:fade={{ duration: 1000, delay: 700 }} animate:flip={{ duration: 700 }}>
                                <PaletteCard {palette} freshlyCreated />
                            </div>
                        {/each}
                    </div>
                </section>
            {/if}
        </div>
    </Container>
</div>

// src/react/src/app/brew/page.tsx
'use client'

import { useState, useEffect, useRef } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import Container from '@/components/Container'
import BrewInput from '@/components/BrewInput'
import PaletteCard from '@/components/PaletteCard'
import { Palette } from '@/types'

export default function BrewPage() {
  const [isFetchingPalette, setIsFetchingPalette] = useState(false)
  const [brewInput, setBrewInput] = useState('')
  const [palettes, setPalettes] = useState<Palette[]>([])
  const palettesRef = useRef<HTMLElement>(null)

  const brew = async () => {
    if (brewInput.length === 0) return
    
    setIsFetchingPalette(true)
    
    try {
      const res = await fetch(`/api/brew?prompt=${encodeURIComponent(brewInput)}`)
      const newPalette = await res.json()
      
      if (res.ok) {
        setPalettes(prev => [newPalette, ...prev])
      } else {
        console.error('Failed to generate palette:', newPalette.error)
      }
    } catch (error) {
      console.error('Error brewing palette:', error)
    } finally {
      setIsFetchingPalette(false)
    }
  }

  // Handle input length limit
  const handleInputChange = (value: string) => {
    if (value.length <= 100) {
      setBrewInput(value)
    }
  }

  // Scroll to palettes when first palette appears
  useEffect(() => {
    if (palettesRef.current && palettes.length === 1) {
      palettesRef.current.scrollIntoView({ behavior: 'smooth' })
    }
  }, [palettes.length])

  return (
    <div className={`animate-fade-in flex flex-1 transition-all duration-700 ${palettes.length === 0 ? 'items-center' : 'items-start pt-10'}`}>
      <Container size="small">
        <div className="my-10">
          {/* Info */}
          <AnimatePresence>
            {palettes.length === 0 && (
              <motion.div
                className="flex flex-col items-center text-center"
                initial={{ opacity: 1 }}
                exit={{ opacity: 0 }}
                transition={{ duration: 0.4 }}
              >
                <p className="font-serif text-3xl font-bold">Brew a palette</p>
                <p className="mt-4 w-full max-w-[550px] text-base text-zinc-600 md:text-lg">
                  Describe the theme of your colors, vibes, or use cases.
                </p>
              </motion.div>
            )}
          </AnimatePresence>

          {/* Prompt */}
          <div className="mt-10">
            <div className="flex flex-col gap-2">
              <BrewInput
                value={brewInput}
                onChange={handleInputChange}
                loading={isFetchingPalette}
                onSubmit={brew}
              />
              <div className="flex w-full items-center justify-end gap-2">
                {brewInput.length > 80 && (
                  <span className="text-sm font-medium text-zinc-500">
                    {brewInput.length}/100
                  </span>
                )}
              </div>
            </div>
          </div>

          {/* Palettes */}
          <AnimatePresence>
            {palettes.length > 0 && (
              <motion.section
                ref={palettesRef}
                className="mt-12 mb-16"
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                transition={{ duration: 0.6, delay: 0.3 }}
              >
                <div className="flex flex-col gap-8">
                  <AnimatePresence>
                    {palettes.map((palette, index) => (
                      <motion.div
                        key={palette.id}
                        layout
                        initial={{ opacity: 0, y: 20 }}
                        animate={{ opacity: 1, y: 0 }}
                        exit={{ opacity: 0, y: -20 }}
                        transition={{ duration: 0.6, delay: 0.3 }}
                      >
                        <PaletteCard 
                          palette={palette} 
                          freshlyCreated={index === 0} 
                        />
                      </motion.div>
                    ))}
                  </AnimatePresence>
                </div>
              </motion.section>
            )}
          </AnimatePresence>
        </div>
      </Container>
    </div>
  )
}
